steps:
  # 0. GradleでJARビルド
  - name: 'gradle'
    entrypoint: 'sh'
    args: ['-c', 'gradle bootJar']

  # 1. Dockerイメージ作成
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'us-west1-docker.pkg.dev/revoxprod/revox-repository/backend:$COMMIT_SHA'
      - '.'

  # 2. DockerイメージをArtifact Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'us-west1-docker.pkg.dev/revoxprod/revox-repository/backend:$COMMIT_SHA'

  # 3. "latest" タグでもプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - tag
      - 'us-west1-docker.pkg.dev/revoxprod/revox-repository/backend:$COMMIT_SHA'
      - 'us-west1-docker.pkg.dev/revoxprod/revox-repository/backend:latest'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'us-west1-docker.pkg.dev/revoxprod/revox-repository/backend:latest'

  # 4. VMにスクリプトをコピー
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - scp
      - update-deploy.sh
      - portfolio-revox:/home/rikutoweb5/revox/update-deploy.sh
      - --zone=us-west1-a
      - --project=revoxprod

  # 5. VM上で権限付与＆スクリプト実行
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - portfolio-revox
      - --zone=us-west1-a
      - --command="cd /home/rikutoweb5/revox && git pull && sudo chmod +x update-deploy.sh && sudo ./update-deploy.sh"
      - --project=revoxprod

options:
  logging: CLOUD_LOGGING_ONLY