# 共通
jwt:
  secret-key: ${JWT_SECRET_KEY}

server:
  port: ${PORT:8080}

---

# 開発環境プロファイル
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: dev
      connection-timeout: 60000
      maximum-pool-size: 5
      connection-test-query: SELECT 1
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: dev

---

# 本番環境プロファイル
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PROD_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: prod
      connection-timeout: 60000
      maximum-pool-size: 8
      connection-test-query: SELECT 1
      initialization-fail-timeout: -1
      leak-detection-threshold: 20000
#      baseline-on-migrate: true


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
    locations: classpath:db/migration
    schemas: prod
#    connect-retries: 10
#    retry-interval: 5s