# 共通
jwt:
  secret-key: ${JWT_SECRET_KEY}

---
# 開発環境プロファイル
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    # 開発環境は dev スキーマを使用
    url: ${DEV_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: dev

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: dev

---
# 本番環境プロファイル
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    # 本番環境は prod スキーマを使用
    url: ${PROD_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: prod

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: prod