spring:
  datasource:
    url: jdbc:mysql://db:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Tokyo&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

gemini:
  api-key: ${GEMINI_API_KEY}
  model: "gemini-2.5-flash"
  project-id: ${GOOGLE_CLOUD_PROJECT}
  location: ${GOOGLE_CLOUD_LOCATION}
  system-instruction: "あなたはバイクの専門家です..."

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}