# 開発環境用設定
spring:
  datasource:
    url: jdbc:h2:file:./data/revoxdb;DB_CLOSE_ON_EXIT=FALSE  # fileで残すため適宜削除が必要です
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update  # validateを使って適宜Flywayとの差分を確認する
    show-sql: true
    properties:
      hibernate:
        format_sql: true