# 共通
jwt:
  secret-key: ${JWT_SECRET_KEY}

---

# 開発環境プロファイル
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_DB_URL}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: dev
      connection-timeout: 30000
      maximum-pool-size: 5
      connection-test-query: SELECT 1
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: dev

---

# 本番環境プロファイル
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PROD_DB_URL}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: prod
      connection-timeout: 30000
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: prod
